#!/usr/bin/python3
'''Script useing async comprehension and generators'''
import asyncio
from typing import List
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    '''Async comprehension function

    Return: list of floats generated by the async generator'''
    result = [i async for i in async_generator()]
    return result
